export const CREATE_EVENT_REQUEST="CREATE_EVENT_REQUEST"
export const CREATE_EVENT_SUCCESS="CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_ERROR="CREATE_EVENT_ERROR"

export const ADD_ATTENDEE_REQUEST="ADD_ATTENDEE_REQUEST"
export const ADD_ATTENDEE_SUCCESS="ADD_ATTENDEE_SUCCESS"
export const ADD_ATTENDEE_ERROR="ADD_ATTENDEE_ERROR"

export const GET_EVENT_REQUEST='GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS='GET_EVENT_SUCCESS';
export const GET_EVENT_ERROR='GET_EVENT_ERROR';