export const CREATE_EVENT_REQUEST="CREATE_EVENT_REQUEST"
export const CREATE_EVENT_SUCCESS="CREATE_EVENT_SUCCESS"
export const CREATE_EVENT_ERROR="CREATE_EVENT_ERROR"

export const EDIT_EVENT_REQUEST="EDIT_EVENT_REQUEST"
export const EDIT_EVENT_SUCCESS="EDIT_EVENT_SUCCESS"
export const EDIT_EVENT_ERROR="EDIT_EVENT_ERROR"

export const DELETE_EVENT_REQUEST="DELETE_EVENT_REQUEST"
export const DELETE_EVENT_SUCCESS="DELETE_EVENT_SUCCESS"
export const DELETE_EVENT_ERROR="DELETE_EVENT_ERROR"

export const ADD_ATTENDEE_REQUEST="ADD_ATTENDEE_REQUEST"
export const ADD_ATTENDEE_SUCCESS="ADD_ATTENDEE_SUCCESS"
export const ADD_ATTENDEE_ERROR="ADD_ATTENDEE_ERROR"

export const REMOVE_ATTENDEE_REQUEST="REMOVE_ATTENDEE_REQUEST"
export const REMOVE_ATTENDEE_SUCCESS="REMOVE_ATTENDEE_SUCCESS"
export const REMOVE_ATTENDEE_ERROR="REMOVE_ATTENDEE_ERROR"

export const GET_EVENT_REQUEST='GET_EVENT_REQUEST';
export const GET_EVENT_SUCCESS='GET_EVENT_SUCCESS';
export const GET_EVENT_ERROR='GET_EVENT_ERROR';

export const GET_HOSTINGEVENT_REQUEST='GET_HOSTINGEVENT_REQUEST';
export const GET_HOSTINGEVENT_SUCCESS='GET_HOSTINGEVENT_SUCCESS';
export const GET_HOSTINGEVENT_ERROR='GET_HOSTINGEVENT_ERROR';

export const GET_ATTENDINGEVENT_REQUEST='GET_ATTENDINGEVENT_REQUEST';
export const GET_ATTENDINGEVENT_SUCCESS='GET_ATTENDINGEVENT_SUCCESS';
export const GET_ATTENDINGEVENT_ERROR='GET_ATTENDINGEVENT_ERROR';